### ISSUE TITLE
does not work with syntax highlighting

### ISSUE THREAD

**Issue by eyJhb** [OhYee/goldmark-plantuml#2]
When enabling this plugin, it breaks the ability to use other extensions such as https://github.com/yuin/goldmark-highlighting

Unsure if this is just a finding I am having.

**Comment by OhYee** [comment]
You should init goldmark like this

```
md := goldmark.New(
		goldmark.WithExtensions(
			extension.GFM,
			ext.NewExt(
				uml.RenderMap(50, "plantuml-svg"),
				ext.RenderMap{
					Languages:      []string{"*"},
					RenderFunction: ext.GetFencedCodeBlockRendererFunc(highlighting.NewHTMLRenderer()),
				},
			),
		),
		goldmark.WithParserOptions(
			parser.WithAutoHeadingID(),
		),
		goldmark.WithRendererOptions(),
	)
```

`RenderFunction: ext.GetFencedCodeBlockRendererFunc(highlighting.NewHTMLRenderer())`  will render fenced code block renderer for highlight

If you have more than one extensions register for rendering fenced codeblock, you can add extensions like this.

https://github.com/OhYee/blotter/blob/7f1426754ded43db9471fb8f1d8e7edd78dcdc68/api/pkg/markdown/main.go#L24-L92

**Comment by eyJhb** [comment]
Thanks, that works perfectly well.

Could this maybe be added in a better way to the readme? Seems to me to be somewhat hidden.

**Comment by OhYee** [comment]
ok, I will update README later

**Comment by eyJhb** [comment]
Thanks! Really appreciate the library and the help! :)
